Services_old/di/inv_mgmt/_src/inventory_app/urls.py
from django.urls import path
from django.urls import re_path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('adminpage/', views.admin_view, name='admin_view'),
    path('adminpage/download_stock_report/', views.download_stock_report, name='download_stock_report'),
    path('get-item-details/<int:item_id>/', views.get_item_details, name='get_item_details'),
    path('get-item-locations/<int:item_id>', views.get_item_locations, name='get_item_locations'),
    path('user/', views.user, name='user'),
    path('stockcheck/', views.stock_check, name='stock_check'),
    re_path(r'^get-items-for-location/(?P<location_name>.+)$', views.get_items_for_location, name='get_items_for_location'),
    path('update-units-by-location/', views.update_units_by_location, name='update_units_by_location'),
    path('submit-withdrawal/', views.submit_withdrawal, name='submit_withdrawal'),
    path('track/', views.track, name='track'),
    path('track-withdrawals/', views.track_withdrawals, name='track_withdrawals'),
    path('order/', views.order, name='order'),
    path('order_view/', views.order_view, name='order_view'),
    path('consolidate-stock/<int:order_id>/', views.consolidate_stock, name='consolidate_stock'),
    path('get-locations-for-item/<int:item_id>/', views.get_locations_for_item, name='get-locations-for-item'),
    path('analyse/', views.analyse, name='analyse'),
    path('item/', views.item_search, name='item_search'),
    path('server-status/', views.server_status, name='server_status'),
    path('get-item-by-barcode/', views.get_item_by_barcode, name='get_item_by_barcode'),
    path('get-item-details/<int:item_id>/', views.get_item_details, name='get_item_details'),

    # Define other URLs for your app
]

Services_old/di/inv_mgmt/_src/inventory_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventory_app.urls')),
]

Services_old/di/inv_mgmt/_src/inventory_app/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date


class Location(models.Model):
    name = models.CharField(max_length=255,  default='Stores')  # A descriptive name for the location
    #best update the location names in the django admin page at the onset of the project.

    def __str__(self):
        return self.name

class InventoryItem(models.Model):
    item = models.CharField(max_length=255)
    item_id = models.CharField(max_length=255, default='No barcode')
    location = models.ForeignKey(Location, on_delete=models.CASCADE, related_name='inventory_items')
    supplier = models.CharField(max_length=255)
    quantity_per_unit = models.CharField(max_length=100)  # Assuming this is a descriptive field
    unit = models.IntegerField()
    minimum_unit = models.IntegerField()
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    supplier_link = models.CharField(max_length=255)


    def __str__(self):
        return self.item

class ItemWithdrawal(models.Model):
    item = models.ForeignKey(InventoryItem, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, blank=True, related_name='withdrawals')
    withdrawal_item_id = models.ForeignKey(InventoryItem, on_delete=models.SET_NULL, null=True, blank=True, related_name='withdrawal_item')
    # item_id = models.CharField(max_length=255, default='No barcode')
    date_withdrawn = models.DateTimeField(default=timezone.now)
    units_withdrawn = models.IntegerField()
    withdrawn_by = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.item} - {self.units_withdrawn} units"


class OrderItem(models.Model):
    item = models.ForeignKey(InventoryItem, on_delete=models.CASCADE, related_name='order_items')
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, blank=True, related_name='order_locations')
    supplier = models.CharField(max_length=255)
    on_order = models.IntegerField(default=0)
    quantity_per_unit = models.CharField(max_length=100)  # Assuming this is a descriptive field
    unit = models.IntegerField()
    minimum_unit = models.IntegerField()
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    request_date = models.DateField()
    requested_by = models.CharField(max_length=255)
    oracle_order_date = models.DateField()
    oracle_po = models.CharField(max_length=255)
    order_lead_time = models.DateField()
    completed = models.BooleanField(default=False)

    def __str__(self):
        return str(self.item)

    def calculate_lead_time(self):
        if self.order_lead_time and self.oracle_order_date:
            return (self.order_lead_time - self.oracle_order_date).days
        return 0

    def days_since_oracle_order(self):
        return (date.today() - self.oracle_order_date).days if self.oracle_order_date else 0

Services_old/di/inv_mgmt/_src/inventory_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import StockUpdateForm, StockAddForm
from .models import InventoryItem, ItemWithdrawal, OrderItem, Location
from django.http import JsonResponse
from django.http import HttpResponse
from io import BytesIO
from openpyxl import Workbook
from django.utils import timezone
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.db.models import F, ExpressionWrapper, fields
from django.db import transaction
from django.db.models import Count, Case, When, IntegerField, Sum, Max, Avg, F
from django.db.models.functions import Coalesce
from urllib.parse import unquote as urlunquote
from django.views.decorators.csrf import csrf_exempt



@csrf_exempt
def get_item_by_barcode(request):
    if request.method == 'POST':
        barcode = request.POST.get('barcode')
        try:
            item = InventoryItem.objects.get(item_id=barcode)
            data = {
                'item_id': item.id,
                'supplier': item.supplier,
                'units': item.unit,
                'minimum_units': item.minimum_unit,
                'cost': item.cost,
                # 'location_id': item.location.id,  # Location ID
                'location_name': item.location.name,  # Location name
            }
            return JsonResponse(data)
        except InventoryItem.DoesNotExist:
            return JsonResponse({'error': 'Item not found'}, status=404)
    return JsonResponse({'error': 'Invalid request'}, status=400)

def get_item_details(request, item_id):
    item = InventoryItem.objects.get(pk=item_id)
    
    data = {
        'supplier': item.supplier,
        'units': item.unit,
        'minimum_units': item.minimum_unit,
        'cost': item.cost,
    }
    
    return JsonResponse(data)

def home(request):
    items = InventoryItem.objects.all()  # Retrieve all inventory items

    # items_on_order = OrderItem.objects.filter(on_order__gt=0).count()
    items_on_order = OrderItem.objects.filter(on_order__gt=0, completed=False).count()
    items_below_minimum = InventoryItem.objects.annotate(difference=ExpressionWrapper(F('unit') - F('minimum_unit'), output_field=fields.IntegerField())).filter(difference__lt=0).count()
    items_5_more_than_minimum = InventoryItem.objects.annotate(difference=ExpressionWrapper(F('unit') - F('minimum_unit'), output_field=fields.IntegerField())).filter(difference=5).count()
    items_greater_than_5_more_than_minimum = InventoryItem.objects.annotate(difference=ExpressionWrapper(F('unit') - F('minimum_unit'), output_field=fields.IntegerField())).filter(difference__gt=5).count()


    items_below_minimum_by_location = InventoryItem.objects.annotate(
        below_minimum=Case(
            When(unit__lt=F('minimum_unit'), then=1),
            default=0,
            output_field=IntegerField()
        )
    ).values('location__name').annotate(total_below_minimum=Sum('below_minimum')).order_by('location__name')

    locations = [item['location__name'] for item in items_below_minimum_by_location]
    below_minimum_counts = [item['total_below_minimum'] for item in items_below_minimum_by_location]


    context = {
        'items': items,
        'items_on_order': items_on_order,
        'items_below_minimum': items_below_minimum,
        'items_5_more_than_minimum': items_5_more_than_minimum,
        'items_greater_than_5_more_than_minimum': items_greater_than_5_more_than_minimum,
        'locations': locations,
        'below_threshold_counts': below_minimum_counts,
    }

    return render(request, 'inventory_app/home.html', context)




def server_status(request):
    return JsonResponse({'status': 'alive'})




def analyse(request):
    items = InventoryItem.objects.all()  # Retrieve all inventory items

    # items_on_order = OrderItem.objects.filter(on_order__gt=0).count()
    items_on_order = OrderItem.objects.filter(on_order__gt=0, completed=False).count()
    items_below_minimum = InventoryItem.objects.annotate(difference=ExpressionWrapper(F('unit') - F('minimum_unit'), output_field=fields.IntegerField())).filter(difference__lt=0).count()
    items_5_more_than_minimum = InventoryItem.objects.annotate(difference=ExpressionWrapper(F('unit') - F('minimum_unit'), output_field=fields.IntegerField())).filter(difference=5).count()
    items_greater_than_5_more_than_minimum = InventoryItem.objects.annotate(difference=ExpressionWrapper(F('unit') - F('minimum_unit'), output_field=fields.IntegerField())).filter(difference__gt=5).count()


    items_below_minimum_by_location = InventoryItem.objects.annotate(
        below_minimum=Case(
            When(unit__lt=F('minimum_unit'), then=1),
            default=0,
            output_field=IntegerField()
        )
    ).values('location__name').annotate(total_below_minimum=Sum('below_minimum')).order_by('location__name')

    locations = [item['location__name'] for item in items_below_minimum_by_location]
    below_minimum_counts = [item['total_below_minimum'] for item in items_below_minimum_by_location]

    ##########################################
    one_week_ago = timezone.now() - timezone.timedelta(days=7)
    # Query to get the total units withdrawn for each item in the last week, then order by the total and take the top 5
    top_withdrawals = ItemWithdrawal.objects.filter(date_withdrawn__gte=one_week_ago).values('item__item').annotate(total_withdrawn=Sum('units_withdrawn')).order_by('-total_withdrawn')[:5]

    items_labels = [withdrawal['item__item'] for withdrawal in top_withdrawals]
    withdrawals_data = [withdrawal['total_withdrawn'] for withdrawal in top_withdrawals]


    ##########################################
    # Query to calculate lead time and get the top 5 items with the longest lead times
    # top_lead_times = OrderItem.objects.annotate(
    #     lead_time=ExpressionWrapper(F('order_lead_time') - F('oracle_order_date'), output_field=fields.DurationField())
    # ).order_by('-lead_time')[:5]

    # items_lead_time_labels = [item.item.item for item in top_lead_times]  # Adjust based on your model's structure
    #    = [item.lead_time.days for item in top_lead_times]
    top_lead_times = OrderItem.objects.annotate(
    lead_time=ExpressionWrapper(F('order_lead_time') - F('oracle_order_date'), output_field=fields.DurationField())
    ).values('item__item') \
    .annotate(max_lead_time=Max('lead_time')) \
    .order_by('-max_lead_time')[:5]

    items_lead_time_labels = [item['item__item'] for item in top_lead_times]
    lead_times = [item['max_lead_time'].days for item in top_lead_times]  # Extracting days from lead time


    ####################EXPERIMENTAL FORECASTING######################

    # Calculate one week ago from now
    one_week_ago = timezone.now() - timezone.timedelta(days=7)

    # Get the average daily withdrawal rate for each item over the last week
    avg_withdrawals_per_item = ItemWithdrawal.objects.filter(date_withdrawn__gte=one_week_ago) \
        .values('item_id') \
        .annotate(avg_daily_withdrawn=Avg('units_withdrawn'))

    # Convert to a dictionary for easier access
    avg_withdrawals_dict = {withdrawal['item_id']: withdrawal['avg_daily_withdrawn'] for withdrawal in avg_withdrawals_per_item}

    # For each inventory item, calculate net stock and estimate days until stock runs out
    items_forecast = []
    for item in InventoryItem.objects.all():
        item_id = item.id
        total_on_order = OrderItem.objects.filter(item_id=item_id, completed=False) \
            .aggregate(total_on_order=Coalesce(Sum('on_order'), 0))['total_on_order']
        
        net_stock = item.unit - total_on_order
        avg_daily_withdrawn = avg_withdrawals_dict.get(item_id, 0)
        # net_stock = item.unit - OrderItem.objects.filter(item_id=item_id, completed=False).aggregate(total_on_order=Sum('on_order'))['total_on_order'] or 0
        
        # Avoid division by zero
        days_until_out = (net_stock / avg_daily_withdrawn) if avg_daily_withdrawn else float('inf')
        
        items_forecast.append({
            'item': item,
            'net_stock': net_stock,
            'avg_daily_withdrawn': avg_daily_withdrawn,
            'days_until_out': days_until_out,
            
        })
        print(items_forecast)



    context = {
        'items': items,
        'items_on_order': items_on_order,
        'items_below_minimum': items_below_minimum,
        'items_5_more_than_minimum': items_5_more_than_minimum,
        'items_greater_than_5_more_than_minimum': items_greater_than_5_more_than_minimum,
        'locations': locations,
        'below_threshold_counts': below_minimum_counts,
        'items_labels': items_labels,
        'withdrawals_data': withdrawals_data,
        'items_lead_time_labels': items_lead_time_labels,
        'lead_times': lead_times,
        'items_forecast': items_forecast,
    }

    return render(request, 'inventory_app/analyse.html', context)


def user(request): #this is the base withdrawal page
    items = InventoryItem.objects.all().order_by('item')  # Adjust ordering as needed
    return render(request, 'inventory_app/user.html', {'items': items})

def stock_check(request):
    # items = InventoryItem.objects.all().order_by('item')
    locations = Location.objects.all().order_by('name')  # Get all locations, order by name
    return render(request, 'inventory_app/stockcheck.html', {'locations': locations})

def get_items_for_location(request, location_name):
    decoded_name = urlunquote(location_name)  # Decode the URL-encoded location name
    location = Location.objects.filter(name=decoded_name).first()
    if location:
        items = InventoryItem.objects.filter(location=location)
        items_data = [{'id': item.id, 'name': item.item, 'units': item.unit} for item in items]
        return JsonResponse({'items': items_data})
    else:
        return JsonResponse({'error': 'Location not found'}, status=404)
    

Services_old/di/inv_mgmt/_src/inventory_app/templates/inventory_app/order.html
{% load static %}
{% load order_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Order Stock</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script>
        $(document).ready(function() {
            // Handler for item selection changes
            $('#item_select').change(function() {
                var itemId = $(this).val();
                if (itemId) {
                    $.getJSON(`/get-locations-for-item/${itemId}/`, function(locations) {
                        var locationSelect = $('#location_select');
                        locationSelect.empty(); // Clear existing options
                        locationSelect.append($('<option>').val('').text('Select a Location'));
                        $.each(locations, function(i, location) {
                            locationSelect.append($('<option>').val(location.id).text(location.name));
                        });
                    }).fail(function() {
                        console.error('Error fetching locations');
                    });
        
                    $.getJSON(`/get-item-details/${itemId}`, function(data) {
                        $('#supplier').val(data.supplier || 'N/A');
                        $('#units').val(data.units);
                        $('#minimum_units').val(data.minimum_units);
                        $('#cost').val(data.cost);
                        $('#withdrawal_date').val(new Date().toISOString().slice(0, 10));
                    }).fail(function() {
                        console.error('Error fetching item details');
                    });
                } else {
                    $('#location_select').empty().append($('<option>').val('').text('Select a Location'));
                    $('#supplier').val('');
                    $('#units').val('');
                    $('#minimum_units').val('');
                    $('#cost').val('');
                }
            });
        
            // Function to apply blinking effect to past dates
            function checkDates() {
                var today = new Date().setHours(0, 0, 0, 0); // Today's date without time part
                $('#stock_table tbody tr').each(function() {
                    var expectedByCell = $(this).find('td').eq(4); // Assuming "Expected by" is the 5th column
                    var expectedDateStr = expectedByCell.text();
                    var expectedDate = new Date(expectedDateStr).setHours(0, 0, 0, 0);
        
                    if (expectedDate < today) {
                        expectedByCell.addClass('blinkingRed');
                    }
                });
            }
        
            // Ensuring the checkDates function runs after any dynamically loaded content
            setTimeout(checkDates, 500); // Adjust delay as necessary
        });
        </script>
        
    

    <!-- <script>
        $(document).ready(function() {
            $('#item_select').change(function() {
                var itemId = $(this).val();
                if (itemId) {
                    $.getJSON(`/get-locations-for-item/${itemId}/`, function(locations) {
                        var locationSelect = $('#location_select');
                        locationSelect.empty(); // Clear existing options
                        locationSelect.append($('<option>').val('').text('Select a Location'));
                        $.each(locations, function(i, location) {
                            locationSelect.append($('<option>').val(location.id).text(location.name));
                        });
                    }).fail(function() {
                        console.error('Error fetching locations');
                    });

                    // Existing code to fetch item details
                    $.getJSON(`/get-item-details/${itemId}`, function(data) {
                        $('#supplier').val(data.supplier || 'N/A');
                        $('#units').val(data.units);
                        $('#minimum_units').val(data.minimum_units);
                        $('#cost').val(data.cost);
                        $('#withdrawal_date').val(new Date().toISOString().slice(0, 10));
                    }).fail(function() {
                        console.error('Error fetching item details');
                        $('#supplier').val('');
                        $('#units').val('');
                        $('#minimum_units').val('');
                        $('#cost').val('');
                    });
                } else {
                    $('#location_select').empty().append($('<option>').val('').text('Select a Location'));
                    $('#supplier').val('');
                    $('#units').val('');
                    $('#minimum_units').val('');
                    $('#cost').val('');
                }
            });
        });

    </script>

    <script>
        $(document).ready(function() {
            // Your existing $(document).ready() code

            // Call checkDates function after the document is fully loaded
            checkDates();
        });

        function checkDates() {
            var today = new Date().setHours(0, 0, 0, 0); // Today's date without time part
            $('#stock_table tbody tr').each(function() {
                // Assuming "Expected by" is the 5th column (index 4)
                var expectedByCell = $(this).find('td').eq(4);
                var expectedDateStr = expectedByCell.text();
                var expectedDate = new Date(expectedDateStr).setHours(0, 0, 0, 0);

                if (expectedDate < today) {
                    // Apply blinking effect if the expected date has passed
                    expectedByCell.addClass('blinkingRed');
                }
            });
        }

    </script> -->

    <script>
        function filterBySecondColumn() {{
        var filterText = document.getElementById('searchInput').value.toLowerCase(); // Convert to lowercase
        var table = document.getElementById('stock_table');
        var tr = table.getElementsByTagName('tr');
    
        for (var i = 0; i < tr.length; i++) {{
            var td = tr[i].getElementsByTagName('td')[1]; // Target the second column (index 1)
            if (td) {{
            var textValue = td.textContent.toLowerCase() || td.innerText.toLowerCase(); // Convert to lowercase
            if (filterText === "" || textValue.includes(filterText)) {{
                tr[i].style.display = "";
            }} else {{
                tr[i].style.display = "none";
            }}
            }} 
        }}
        }}
  </script>

    <link rel="stylesheet" href="{% static 'inventory_app/css/admin.css' %}">

    <style>
    @keyframes blinker {  
        50% { background-color: red; }
      }
      
    .blinkingRed {
        animation: blinker 1s linear infinite;
        color: white; /* Ensure text is readable against the red background */
      }
    </style>
</head>


<body>
    <h1>Order Stock</h1>

    <div class="button-container">
        <form action="/" method="get">
          <button type="submit">Home</button>
        </form>
    </div>

    <div class="container">
        <div class="left">
            <h2>Place Order</h2>
        <form id="itemForm" method="POST" action="{% url 'order_view' %}">
            {% csrf_token %}
        <label for="item_select">Item:</label>
        <select id="item_select" name="item">
            <option value="">Select an Item</option>
            {% for item in items %}
            <option value="{{ item.id }}">{{ item.item }}</option>
            {% endfor %}
        </select>

        <label for="location_select">Location:</label>
        <select id="location_select" name="location">
            <option value="">Select a Location</option>
            <!-- Options will be added dynamically based on the item selected -->
        </select>
        <!-- <input type="text" id="location" name="location" readonly> -->

        <label for="supplier">Supplier:</label>
        <input type="text" id="supplier" name="supplier" readonly>

        <label for="units">Units available:</label>
        <input type="text" id="units" name="units" readonly>

        <label for="minimum_units">Minimum Units:</label>
        <input type="text" id="minimum_units" name="minimum_units" readonly>

        <label for="cost">Cost:</label>
        <input type="text" id="cost" name="cost" readonly>

        <label for="id_unit_ord">Units ordered:</label>
        <input type="text" id="id_unit_ord" name="unit_ord">

        <label for="id_request_date">Request Date:</label>
        <input type="date" id="id_request_date" name="request_date">

        <label for="id_requested_by">Requested By:</label>
        <input type="text" id="id_requested_by" name="requested_by">

        <label for="id_oracle_order_date">Oracle Order Date:</label>
        <input type="date" id="id_oracle_order_date" name="oracle_order_date">

        <label for="id_oracle_po">Oracle PO:</label>
        <input type="text" id="id_oracle_po" name="oracle_po">

        <label for="id_order_lead_time">Order Lead Time:</label>
        <input type="date" id="id_order_lead_time" name="order_lead_time">

        <br><br>
        <button type="submit">Submit</button>
    </form>
</div>





<div class="right">
    <div class="tile">
      <h2>On Order</h2>
      <input type="text" id="searchInput" onkeyup="filterBySecondColumn()" placeholder="Search for items...">
      <table id="stock_table">
        <thead>
          <tr>
            <th>Item</th>
            <th>Location</th>
            <th>Units Ordered</th>
            <th>Oracle Order</th>
            <th>Expected by</th>
            <!-- <th>Request date</th> -->
            <!-- <th>Ordered by</th> -->
            <th>PO number ref.</th>
            <th>Ordered by</th>
            <th>Order Cost</th>
            <th>Consolidate Stock</th>
            <!-- <th>Order</th> -->
          </tr>
        </thead>
        <tbody>
          {% for item in orders %}
            {% if not item.completed %}
              <tr>
                  <td>{{ item.item }}</td>
                  <td>{{ item.location }}</td>
                  <td>{{ item.on_order }}</td>
                  <td>{{ item.oracle_order_date }}</td>
                  <td>{{ item.order_lead_time }}</td>
                  <td>{{ item.oracle_po }}</td>
                  <td>{{ item.requested_by }}</td>
                  <td>{{ item.on_order|multiply:item.cost }}</td>
                  <td><button type="button" onclick="completeOrder(this)" data-order-id="{{ item.id }}">Complete Order</button></td>
              </tr>
              {% endif %}
          {% endfor %}
      </tbody>
      </table>
    </div>
  </div>
    </div>

<script>
    function completeOrder(button) {
    var orderId = $(button).data('order-id');
    $.ajax({
        url: `/consolidate-stock/${orderId}/`,
        type: 'POST',
        data: {
            csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
            order_id: orderId,
        },
        success: function(response) {
            if(response.success) {
                $(button).closest('tr').remove(); // Remove row on success
                alert(response.message);
            } else {
                alert(response.message);
            }
        }
    });
}
</script>

{% if messages %}
<script>
    window.onload = function() {
        {% for message in messages %}
        alert("{{ message }}");
        {% endfor %}
    }
</script>
{% endif %}
</body>
</html>


   

Services_old/di/inv_mgmt/_src/inventory_app/templates/inventory_app/track.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>Inventory Tracking</title>
  <link rel="stylesheet" href="{% static 'inventory_app/css/home.css' %}">

  <script>
    function filterBySecondColumn() {{
      var filterText = document.getElementById('searchInput').value.toLowerCase(); // Convert to lowercase
      var table = document.getElementById('stock_table');
      var tr = table.getElementsByTagName('tr');
  
      for (var i = 0; i < tr.length; i++) {{
        var td = tr[i].getElementsByTagName('td')[0]; // Target the second column (index 1)
        if (td) {{
          var textValue = td.textContent.toLowerCase() || td.innerText.toLowerCase(); // Convert to lowercase
          if (filterText === "" || textValue.includes(filterText)) {{
            tr[i].style.display = "";
          }} else {{
            tr[i].style.display = "none";
          }}
        }} 
      }}
    }}
  </script>

<script>
  function filterByThirdColumn() {{
    var filterText = document.getElementById('searchInput2').value.toLowerCase(); // Convert to lowercase
    var table = document.getElementById('stock_table');
    var tr = table.getElementsByTagName('tr');

    for (var i = 0; i < tr.length; i++) {{
      var td = tr[i].getElementsByTagName('td')[1]; // Target the second column (index 1)
      if (td) {{
        var textValue = td.textContent.toLowerCase() || td.innerText.toLowerCase(); // Convert to lowercase
        if (filterText === "" || textValue.includes(filterText)) {{
          tr[i].style.display = "";
        }} else {{
          tr[i].style.display = "none";
        }}
      }} 
    }}
  }}
</script>
</head>

<body>
<h1>Item Withdrawal Tracking</h1>

<div class="button-container">
    <form action="/" method="get">
      <button type="submit">Home</button>
    </form>


<!-- <form action="" method="get">
    <button type="submit" name="export">Export as Excel</button>
</form> -->
</div>

<!-- <form method="get">
    <label for="withdrawn_by">Withdrawn By:</label>
    <input type="text" id="withdrawn_by" name="withdrawn_by" value="{{ request.GET.withdrawn_by }}">

    <label for="item">Item:</label>
    <select id="item" name="item">
        <option value="">All Items</option>
        {% for item in items %}
        <option value="{{ item.id }}" {% if request.GET.item == item.id|stringformat:"s" %}selected{% endif %}>{{ item.item }}</option>
        {% endfor %}
    </select>

    <button type="submit">Filter</button>
    <a href="?export">Export as CSV</a>
</form> -->

<input type="text" id="searchInput" onkeyup="filterBySecondColumn()" placeholder="Search by Item...">
<input type="text" id="searchInput2" onkeyup="filterByThirdColumn()" placeholder="Search by Location...">

<table id="stock_table">
    <tr>
        <th>Item</th>
        <th>Location</th>
        <th>Date Withdrawn</th>
        <th>Units Withdrawn</th>
        <th>Withdrawn By</th>
    </tr>
    {% for withdrawal in withdrawals %}
    <tr>
        <td>{{ withdrawal.item }}</td>
        <td>{{ withdrawal.location }}</td>
        <td>{{ withdrawal.date_withdrawn }}</td>
        <td>{{ withdrawal.units_withdrawn }}</td>
        <td>{{ withdrawal.withdrawn_by }}</td>
    </tr>
    {% endfor %}
</table>
</body>
</html>